### ISSUE TITLE
Add test to circle yml for libs to make sure that it has been built

### ISSUE THREAD

**Issue by dancoates** [bigdatr/bigdatr-startr#70]
```yaml
test:
  override:
    - yarn run build
    - test -z "$(git status --porcelain)"
    - yarn run test-all

```
